# Build notebook image: docker build -f Dockerfile-cluster -t tvb-inv-cluster --build-arg CACHE="$(date)" --build-arg TOKEN=<github_security_token> .
FROM continuumio/miniconda3

RUN apt-get -y update && apt-get -y install build-essential gcc

USER root
RUN cd /opt; \
    git clone --depth 1 --branch master https://github.com/popaula937/tvb-root.git

RUN conda update -n base -c defaults conda

RUN conda create -y --name tvb-run python=3.8
RUN /opt/conda/envs/tvb-run/bin/pip install --upgrade pip
RUN /opt/conda/envs/tvb-run/bin/pip install numpy==1.21.0
RUN conda install -y --name tvb-run nomkl numba scipy networkx scikit-learn cython pip numexpr psutil gevent
RUN conda install -y --name tvb-run pytables simplejson cherrypy docutils werkzeug
RUN /opt/conda/envs/tvb-run/bin/pip install scikit-image==0.14.2 h5py formencode cfflib flask==1.1.4 jinja2==2.11.3 nibabel sqlalchemy
RUN /opt/conda/envs/tvb-run/bin/pip install pyAesCrypt

COPY simulation_hpc_launcher.py /opt/tvb-root/framework_tvb/tvb/core

RUN cd /opt/tvb-root; \
    git pull; \
    cd scientific_library; \
    /opt/conda/envs/tvb-run/bin/python setup.py install; \
    cd ../framework_tvb; \
    /opt/conda/envs/tvb-run/bin/python setup.py develop --no-deps; \
    cd ../tvb_storage; \
    /opt/conda/envs/tvb-run/bin/python setup.py develop --no-deps

#ARG TOKEN=github_security_tokenq
#RUN cd /opt; \
#    git clone --depth 1 --branch refactoring https://$TOKEN@github.com/the-virtual-brain/tvb-inversion.git
#
#ARG CACHE=now

#RUN /opt/conda/envs/tvb-run/bin/pip install torch sbi==0.17.2
#
#
#RUN cd /opt/tvb-inversion; \
#    git pull; \
#    cd mpr_sbi_tvb; \
#    cp -R notebooks $HOME/work/; \
#    /opt/conda/envs/tvb-run/bin/python setup.py install
#
#WORKDIR /opt/tvb-inversion/mpr_sbi_tvb