# Build notebook image: docker build -f Dockerfile-notebook -t notebook --build-arg CACHE="$(date)" --build-arg TOKEN=<github_security_token> .
FROM jupyter/datascience-notebook:python-3.8.8

RUN julia -e "using Pkg; pkg\"add Distributions\""
RUN /opt/conda/bin/pip install julia
RUN /opt/conda/bin/python -c "import julia; julia.install()"

USER root
RUN cd /opt; \
    git clone --depth 1 --branch TVB-2892-chunks https://github.com/i-Zaak/tvb-root.git

RUN cd /opt/tvb-root; \
    git pull; \
    cd scientific_library; \
    /opt/conda/bin/python setup.py install

ARG TOKEN=github_security_token
RUN cd /opt; \
    git clone --depth 1 --branch refactoring https://$TOKEN@github.com/the-virtual-brain/tvb-inversion.git

ARG CACHE=now

COPY oauth.py /home/jovyan/.ipython/profile_default/startup/start.py
RUN cd /opt/tvb-inversion; \
    git pull; \
    cd mpr_sbi_tvb; \
    cp -R notebooks $HOME/work/; \
    /opt/conda/bin/python setup.py develop; \
    cd ../mpr_sbi_julia; \
    cp -R notebooks $HOME/work/; \
    /opt/conda/bin/python setup.py develop

RUN chown -R $NB_UID:$NB_UID $HOME

USER $NB_UID
WORKDIR $HOME