# Build notebook image: docker build -f Dockerfile-hpc -t tvb-inversion-hpc --build-arg CACHE="$(date)" --build-arg TOKEN=<github_security_token> .
FROM continuumio/miniconda3

RUN apt-get -y update && apt-get -y install build-essential gcc
RUN apt-get -y update && apt-get -y install texlive-base texlive-formats-extra


RUN conda update -n base -c defaults conda
RUN conda create -y --name tvb-run python=3 nomkl numba scipy numpy networkx scikit-learn cython pip numexpr psutil
RUN conda install -y --name tvb-run pytest pytest-cov pytest-benchmark pytest-mock pytest-xdist matplotlib-base
RUN conda install -y --name tvb-run psycopg2 pytables simplejson cherrypy docutils werkzeug h5py
RUN /opt/conda/envs/tvb-run/bin/pip install --upgrade pip
RUN /opt/conda/envs/tvb-run/bin/pip install  formencode cfflib flask==1.1.4 jinja2==2.11.3 nibabel sqlalchemy alembic # h5py and jinja2 versions are constrained by allensdk
RUN conda install -y --name tvb-run -c conda-forge gevent
RUN /opt/conda/envs/tvb-run/bin/pip install BeautifulSoup4 subprocess32 flask-restx python-keycloak mako pyAesCrypt pyunicore==0.6.0 cython SimpleITK

USER root
RUN cd /opt; \
    git clone --depth 1 --branch master https://github.com/popaula937/tvb-root.git

RUN cd /opt/tvb-root; \
    git pull; \
    cd scientific_library; \
    /opt/conda/envs/tvb-run/bin/python setup.py install

ARG TOKEN=github_security_token
RUN cd /opt; \
    git clone --depth 1 --branch refactoring https://$TOKEN@github.com/the-virtual-brain/tvb-inversion.git

ARG CACHE=now

COPY oauth.py /home/jovyan/.ipython/profile_default/startup/start.py
RUN cd /opt/tvb-inversion; \
    git pull; \
    cd mpr_sbi_tvb; \
    python setup.py develop
